author: CN-LanBao
env: dev  # 环境（dev/prod/test）
path:
  test_suite_dir: "./test_suite"  # 测试用例目录
  report_root_dir: "./result"     # 报告根目录
  log_root_dir: "./logs"          # 日志根目录
device:
  adb_path: "adb"  # ADB路径（默认系统环境变量）
  atx_version: "0.10.0"  # 期望atx-agent版本
allure:
  report_title: "report_{{task_id}}"  # 动态标题（含任务ID）
test:
  pytest_timeout: 3600
  allure_clean: true
  allure_generate_timeout: 600  # Allure生成超时（10分钟）
  report_compress: false         # 启用报告压缩
  report_compress_format: zip   # 压缩格式（zip/tar）
  keep_allure_raw: false        # 压缩后删除原始HTML目录
web:
  host: "0.0.0.0"
  port: 5000
  debug: true