author: CN-LanBao
env: dev  # 环境（dev/prod/test）
path:
  test_suite_dir: "./test_suite"  # 测试用例目录
  report_root_dir: "./result"     # 报告根目录
  log_root_dir: "./logs"          # 日志根目录
device:
  adb_path: "adb"  # ADB路径（默认系统环境变量）
  atx_version: "0.10.0"  # 期望atx-agent版本
test:
  pytest_timeout: 3600  # 测试超时时间（秒）
  allure_clean: true    # 生成报告前清理旧数据
web:
  host: "0.0.0.0"
  port: 5000
  debug: true